### ISSUE TITLE
Avoid escaping OAuth2 scope values in XUI Login page

### ISSUE THREAD

**Issue by gazal-k** [OpenRock/OpenAM#3]
Currently the scopes are displayed like this:

![screenshot from 2015-11-06 14 51 47](https://cloud.githubusercontent.com/assets/8210299/10993610/0519986a-8496-11e5-80db-38dfba0b40b6.png)

Instead of:

![screenshot from 2015-11-06 14 45 50](https://cloud.githubusercontent.com/assets/8210299/10993613/0c365b6a-8496-11e5-837d-d3fd07fb9ef5.png)

**Comment by ilgrosso** [comment]
Please report bugs at https://bugster.forgerock.org/jira/browse/OPENAM
